config/routes.rb
Rails.application.routes.draw do
  devise_for :mechanics, :controllers => {registrations: 'registrations'}

  get '/' => 'mechanics#home'

  resources :customers, except: [:show, :destroy]

  resources :mechanics, only: [:show] do 
    resources :jobs
  end

  post '/jobs' => 'jobs#create'
  post '/complete' => 'work_orders#complete'

  get '/auth/facebook/callback' => 'sessions#create'

  get '/jobs' => 'jobs#jobs'
  get '/get_mechanic_pending_jobs' => 'jobs#mechanic_pending_jobs'
  get '/get_mechanic_completed_jobs' => 'jobs#mechanic_completed_jobs'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :jobs
  has_many :mechanics, through: :jobs

  validates :name, presence: true, uniqueness: true

end

app/models/job.rb
class Job < ActiveRecord::Base

  belongs_to :customer
  belongs_to :mechanic
  has_many :work_orders, dependent: :destroy

  validates :customer_id, presence: true
  validates :mechanic_id, presence: true

  def work_orders_attributes=(attributes)
    self.save
    attributes.each do |k, v|
      order = WorkOrder.find_or_create_by(id: v[:id])
      order.update(description: v[:description], price: v[:price], job_id: self.id)
    end
  end

  def complete?
    work_orders.pluck(:status).all? { |status| status == 1 }
  end

  def self.unfinished_jobs
    includes(:work_orders).where(work_orders: { status: 0 })
  end

  def self.finished_jobs
    includes(:work_orders).where(work_orders: { status: 1 }).select(&:complete?)
  end

end

app/models/mechanic.rb
class Mechanic < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :customers, through: :jobs

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  def unfinished_jobs
    unfinished = []
    self.jobs.each do |job|
      if !job.complete?
        unfinished << job
      end
    end
    unfinished
  end

  def finished_jobs
    finished = []
    self.jobs.each do |job|
      if job.complete?
        finished << job
      end
    end
    finished
  end

end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base

  belongs_to :job
  validates :description, presence: true
  validates :price, presence: true

  enum status: [:pending, :completed]

  def self.mark_complete_by_ids(ids)
    ids.each do |id|
       order = WorkOrder.find_by(id: id)
       order.update(status: 1)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path
    else
      render 'new'
    end
  end

  def edit
    set_customer
  end

  def update
    set_customer
    @customer.update(customer_params)
    redirect_to customers_path
  end

  private
    def customer_params
      params.require(:customer).permit(:name)
    end

    def set_customer
      @customer = Customer.find(params[:id])
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_mechanic, only: [:new, :show, :edit, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def new
    @job = Job.new
    3.times do
      @job.work_orders.build
    end
  end

  def create
    @job = Job.new(job_params)
    @mechanic = Mechanic.find_by(id: params[:job][:mechanic_id])
    if @job.save
      render json: @job, status: 201
    else
      render 'new'
    end
  end

  def show
    @job = []
    @job << Job.find(params[:id])
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to mechanic_job_path(@job.mechanic.id, @job.id)
    else
      render 'edit'
    end
  end

  def destroy
    @job.destroy
    redirect_to '/'
  end

  def jobs
    params[:scoped] ? scope = current_mechanic : scope = Job
    if params[:state] == 'completed'
      render json: scope.finished_jobs
    else
      render json: scope.unfinished_jobs
    end
  end

  private
    
    def set_job
      @job = Job.find(params[:id])
    end

    def set_mechanic
      @mechanic = Mechanic.find_by(id: params[:mechanic_id])
    end

    def job_params
      params.require(:job).permit(:mechanic_id, :customer_id, work_orders_attributes: [:description, :price, :id])
    end

end

app/controllers/mechanics_controller.rb
class MechanicsController < ApplicationController

  def home
    if !current_mechanic
      render 'static/visitor'
    end
    @mechanic = current_mechanic
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:mechanic).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:mechanic).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def verify

  end

  def create
    mechanic = Mechanic.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']

      # this is horrible, but pw can't be blank, eventually make prompt to immedidately set new pw
      u.password = "password"
    end
    sign_in(mechanic)
    session[:mechanic_id] = mechanic.id
    redirect_to mechanic_path(mechanic)
  end

  def auth
    request.env['omniauth.auth']
  end

  def destroy
    session.destroy
    redirect_to '/'
  end

end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController

  def complete
    WorkOrder.mark_complete_by_ids(params[:ids])
    redirect_to '/'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/mechanics_helper.rb
module MechanicsHelper
end

app/views/customers/edit.html.erb
<br><br>
<div class="col-lg-6 col-lg-offset-3">
  <%= form_for @customer do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</div>  

app/views/customers/index.html.erb
<div class="col-lg-6 col-lg-offset-3">
  <%= link_to "Add Customer", new_customer_path %><br><br>

  <% @customers.each do |cust| %>
    <%= link_to cust.name, edit_customer_path(cust) %><br>
  <% end %>
</div>

app/views/customers/new.html.erb
<%= render partial: '/jobs/display_errors', locals: {job: @customer} %>

<div class="col-lg-6 col-lg-offset-3">
  <%= form_for @customer do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %><br>
    <%= f.submit %>
  <% end %>
</div>

app/views/jobs/_display_errors.html.erb
<% if job.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(job.errors.count, "error") %>
      prohibited this object from being saved:
    </h2>
 
    <ul>
    <% job.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %><br>

app/views/jobs/_job_form.html.erb
<div class="col-lg-6 col-lg-offset-3">
  <%= f.label :mechanic_id %>
    <%= f.collection_select :mechanic_id, Mechanic.all, :id, :name, {selected: mechanic_id} %><br><br>

    <%= f.label :customer_id %>
    <%= f.collection_select :customer_id, Customer.all, :id, :name %><br><br>

    <div>
      <%= f.fields_for :work_orders do |builder| %>
        <h4>Work Order:</h4>
        <%= builder.label :description %>
        <%= builder.text_field :description %><br><br>

        <%= builder.label :price %>
        <%= builder.text_field :price %><br><br>
      <% end %>
    </div>

  <%= f.submit id: 'create-job' %>
</div>

app/views/jobs/edit.html.erb
<%= render partial: 'display_errors', locals: {job: @job} %>

<%= form_for @job, :url => url_for(:controller => 'jobs', :action => 'update'), method: :patch do |f| %>
  <%= render partial: 'job_form', locals: {f: f, mechanic_id: @mechanic.id} %>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(function(){
    $('#create-job').removeAttr('id');
  });
</script>

app/views/jobs/new.html.erb
<%= render partial: 'display_errors', locals: {job: @job} %>

<%= form_for @job do |f| %>
  <%= render partial: 'job_form', locals: {f: f, mechanic_id: @mechanic.id} %>
<% end %><br><br>

<div class="col-lg-6 col-lg-offset-3">
  <ul id="new-ajax-jobs"></ul>
</div>

app/views/jobs/show.html.erb
<%= form_tag('/complete') do %>
<%= render partial: '/mechanics/job_list', locals: {job_collection: @job} %>
<%= submit_tag("Mark Selected Complete") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAssessment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application'%>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar-default container-fluid">
  <% if current_mechanic %>
    <span>Logged in as <%= current_mechanic.name %>.  |  </span>
    <span id="home-link"><%= link_to "Home", "/" %>  |  </span>
    <span><%= link_to "Log Out", destroy_mechanic_session_path, method: :delete %></span>
  <% else %>
    <span><%= link_to "Sign Up", new_mechanic_registration_path %>  |  <span>
    <span><%= link_to "Sign In", new_mechanic_session_path %>  |  </span>
    <span><%= link_to "Log In with Facebook", '/auth/facebook' %></span>
  <% end %>
  <br><br><br>
</nav>

<%= yield %>

</body>
</html>

app/views/mechanics/_job_list.html.erb
<ul>
<% job_collection.each do |job| %>
  <li>Mechanic: <%= job.mechanic.name %><br>Customer: <%= job.customer.name %><br>
    <ul>
      <% job.work_orders.each do |order| %>
        <li>
          <%= order.description %>, $<%= order.price %>, <strong><%= order.status %></strong><% if order.status == 'pending' %>, mark complete? <input type="checkbox" name="ids[]" value="<%= order.id %>">
          <% end %><br>
        </li>
      <% end %>
    </ul>
  </li>
  <%= link_to "Edit Job", edit_mechanic_job_path(job.mechanic, job) %>  |  
  <%= link_to "Delete Job", "/mechanics/#{job.mechanic.id}/jobs/#{job.id}", method: :delete %><br><br>
<% end %>
</ul>

app/views/mechanics/_navbar.html.erb
<nav class="navbar container-fluid col-lg-6 col-lg-offset-3">
  <span><%= link_to "Create a New Job", new_mechanic_job_path(mech) %></span>  |  
  <span><%= link_to "Add a Customer", new_customer_path %></span>  |  
  <span><%= link_to "View All Customers", customers_path %></span><br><br>
  <button id="home-button" class="btn-primary">View All Jobs</button>  |  
  <button id="profile-button" class="btn-primary">View Your Jobs</button>
</nav>

app/views/mechanics/home.html.erb
<h1 class="col-lg-6 col-lg-offset-3">Welcome to Fender Unbender!</h3>

<%= render partial: "navbar", locals: {mech: @mechanic} %>

<div class="col-lg-6 col-lg-offset-3">
  <h4 id="pending-header">All Pending Jobs:</h4>
  <%= form_tag('/complete') do %>
  <div id="pending-list">
  </div>
  <%= submit_tag "Mark Selected Complete", :id => 'mark-complete', :class => 'btn-success' %>
  <% end %>
</div>


<div class="col-lg-6 col-lg-offset-3">
  <h4 id="completed-header">All Completed Jobs:</h4>
  <div id="completed-list">
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $(function(){
    setHeaders("All");
    appendPendingJobs('/jobs?state=pending');
    appendCompletedJobs('/jobs?state=completed');
  });
</script>